import { Button } from '@chakra-ui/react';
import { getIsConnected } from 'store/reducers/web3';
import { GetStaticProps } from 'next';
import { inherit } from 'utils/web3/heritage';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppSelector } from 'store/hooks';
import { useState } from 'react';
import { useTranslation } from 'next-i18next';
import Head from 'next/head';

const Claim = () => {
  const { t } = useTranslation('common');
  const [isInheriting, setIsInheriting] = useState<boolean>(false);

  const isConnected: boolean = useAppSelector(getIsConnected);

  async function handleClick() {
    try {
      setIsInheriting(true);

      await inherit();
    } catch (error) {
      alert(error);
    } finally {
      setIsInheriting(false);
    }
  }

  return (
    <div>
      <Head>
        <title>Peace | Claim</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <Button 
            colorScheme='blue' 
            disabled={ !isConnected }
            height='44px'
            isLoading={isInheriting}
            onClick={handleClick}
          >
            { t('claim.claim') }
          </Button>
      </div>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ defaultLocale = "en", locale }) => {
  const translations = await serverSideTranslations(locale || defaultLocale, ['common']);

  return {
    props: {
      ...translations
    }
  };
}

export default Claim;
