import { getInheritor } from 'store/reducers/web3';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppSelector } from 'store/hooks';
import Head from 'next/head';
import Testament from 'components/testament';

const Claim = () => {
  const inheritor = useAppSelector(getInheritor);

  return (
    <div>
      <Head>
        <title>Peace | Claim</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        {
          inheritor === undefined ?
            <div>{ `You don't have an active testament` }</div> :
            <Testament isInheritor testator={ inheritor } />
        }
      </div>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ defaultLocale = 'en', locale }) => {
  const translations = await serverSideTranslations(locale || defaultLocale, ['common']);

  return {
    props: {
      ...translations
    }
  };
}

export default Claim;
