import { GetStaticProps } from 'next';
import { getTestator } from 'store/reducers/web3';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppSelector } from 'store/hooks';
import ConnectBanner from 'components/connect-banner';
import CreatePlan from 'components/create-plan';
import Head from 'next/head';

function Home() {
  const testator = useAppSelector(getTestator);

  return (
    <div>
      <Head>
        <title>Peace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ConnectBanner />

      <CreatePlan /> 
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ defaultLocale = 'en', locale }) => {
  const translations = await serverSideTranslations(locale || defaultLocale, ['common']);

  return {
    props: {
      ...translations
    }
  };
}

export default Home;
