import CreatePlan from 'components/create-plan';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Peace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <CreatePlan />
      </div>
    </div>
  )
}
