import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';

const NFT = () => {
  return (
    <div>
      <Head>
        <title>Peace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      NFT
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ defaultLocale = 'en', locale }) => {
  const translations = await serverSideTranslations(locale || defaultLocale, ['common']);

  return {
    props: {
      ...translations
    }
  };
}

export default NFT;
